-- Add IC_NUMBER column to EMPLOYEE table and update USERS view
-- Run this in Oracle SQL Developer as VITALITY user

-- Step 1: Add IC_NUMBER column to EMPLOYEE table
ALTER TABLE EMPLOYEE ADD ICNUMBER VARCHAR2(100);

-- Step 2: Set default values (14-digit Malaysian IC format examples)
UPDATE EMPLOYEE SET ICNUMBER = '010203010001' WHERE EMPLOYEEID = 101;
UPDATE EMPLOYEE SET ICNUMBER = '010203010002' WHERE EMPLOYEEID = 102;
UPDATE EMPLOYEE SET ICNUMBER = '010203010003' WHERE EMPLOYEEID = 201;
UPDATE EMPLOYEE SET ICNUMBER = '010203010004' WHERE EMPLOYEEID = 202;
UPDATE EMPLOYEE SET ICNUMBER = '010203010005' WHERE EMPLOYEEID = 203;
UPDATE EMPLOYEE SET ICNUMBER = '010203010006' WHERE EMPLOYEEID = 204;
UPDATE EMPLOYEE SET ICNUMBER = '010203010007' WHERE EMPLOYEEID = 205;
UPDATE EMPLOYEE SET ICNUMBER = '010203010008' WHERE EMPLOYEEID = 206;
UPDATE EMPLOYEE SET ICNUMBER = '010203010009' WHERE EMPLOYEEID = 207;

COMMIT;

-- Step 3: Recreate the USERS view to include IC_NUMBER from actual column
CREATE OR REPLACE VIEW USERS AS
SELECT 
    EMPLOYEEID as USER_ID,
    EMAIL as EMAIL,
    EMPLOYEENAME as NAME,
    PASSWORD as PASSWORD,
    EMPLOYEEROLE as USER_ROLE,
    EMPLOYEEADDRESS as ADDRESS,
    EMPLOYEERATE as RATE,
    EMPLOYEEHIREDON as HIRED_ON,
    ANNUALLEAVEBALANCE as ANNUAL_LEAVE_BALANCE,
    SICKLEAVEBALANCE as SICK_LEAVE_BALANCE,
    EMERGENCYLEAVEBALANCE as EMERGENCY_LEAVE_BALANCE,
    SUPERVISOREMPLOYEEID as SUPERVISOR_ID,
    REMEMBER_TOKEN as REMEMBER_TOKEN,
    EMPLOYEENUMBER as PHONE,
    ICNUMBER as IC_NUMBER
FROM EMPLOYEE;

-- Step 4: Update the INSERT trigger to handle IC_NUMBER
CREATE OR REPLACE TRIGGER TRG_USERS_INSERT
INSTEAD OF INSERT ON USERS
FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENUMBER, EMAIL, EMPLOYEENAME, PASSWORD, EMPLOYEEROLE, EMPLOYEEADDRESS, EMPLOYEERATE, EMPLOYEEHIREDON, ANNUALLEAVEBALANCE, SICKLEAVEBALANCE, EMERGENCYLEAVEBALANCE, SUPERVISOREMPLOYEEID, REMEMBER_TOKEN, ICNUMBER)
    VALUES (
        NVL(:NEW.USER_ID, (SELECT NVL(MAX(EMPLOYEEID),0)+1 FROM EMPLOYEE)),
        :NEW.PHONE,
        :NEW.EMAIL,
        :NEW.NAME,
        :NEW.PASSWORD,
        NVL(:NEW.USER_ROLE, 'Staff'),
        :NEW.ADDRESS,
        NVL(:NEW.RATE, 3000),
        NVL(:NEW.HIRED_ON, SYSDATE),
        NVL(:NEW.ANNUAL_LEAVE_BALANCE, 14),
        NVL(:NEW.SICK_LEAVE_BALANCE, 10),
        NVL(:NEW.EMERGENCY_LEAVE_BALANCE, 5),
        :NEW.SUPERVISOR_ID,
        :NEW.REMEMBER_TOKEN,
        :NEW.IC_NUMBER
    );
END;
/

-- Step 5: Update the UPDATE trigger to handle IC_NUMBER
CREATE OR REPLACE TRIGGER TRG_USERS_UPDATE
INSTEAD OF UPDATE ON USERS
FOR EACH ROW
BEGIN
    UPDATE EMPLOYEE SET
        EMPLOYEENUMBER = :NEW.PHONE,
        EMAIL = :NEW.EMAIL,
        EMPLOYEENAME = :NEW.NAME,
        PASSWORD = :NEW.PASSWORD,
        EMPLOYEEROLE = :NEW.USER_ROLE,
        EMPLOYEEADDRESS = :NEW.ADDRESS,
        EMPLOYEERATE = :NEW.RATE,
        EMPLOYEEHIREDON = :NEW.HIRED_ON,
        ANNUALLEAVEBALANCE = :NEW.ANNUAL_LEAVE_BALANCE,
        SICKLEAVEBALANCE = :NEW.SICK_LEAVE_BALANCE,
        EMERGENCYLEAVEBALANCE = :NEW.EMERGENCY_LEAVE_BALANCE,
        SUPERVISOREMPLOYEEID = :NEW.SUPERVISOR_ID,
        REMEMBER_TOKEN = :NEW.REMEMBER_TOKEN,
        ICNUMBER = :NEW.IC_NUMBER
    WHERE EMPLOYEEID = :OLD.USER_ID;
END;
/

COMMIT;

-- Verify the column was added
SELECT EMPLOYEEID, EMPLOYEENAME, ICNUMBER, EMAIL FROM EMPLOYEE ORDER BY EMPLOYEEID;
