-- Add EMAIL and PASSWORD columns - SIMPLE VERSION
-- Run this in Oracle as VITALITY user

-- Step 1: Add the columns
ALTER TABLE EMPLOYEE ADD EMAIL VARCHAR2(100);
ALTER TABLE EMPLOYEE ADD PASSWORD VARCHAR2(255);
ALTER TABLE EMPLOYEE ADD REMEMBER_TOKEN VARCHAR2(100);

-- Step 2: Set EASY credentials for ALL employees
-- Password hash is for: 123456
UPDATE EMPLOYEE SET EMAIL = 'admin@test.com', PASSWORD = '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi' WHERE EMPLOYEEID = 101;
UPDATE EMPLOYEE SET EMAIL = 'admin2@test.com', PASSWORD = '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi' WHERE EMPLOYEEID = 102;
UPDATE EMPLOYEE SET EMAIL = 'staff1@test.com', PASSWORD = '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi' WHERE EMPLOYEEID = 201;
UPDATE EMPLOYEE SET EMAIL = 'staff2@test.com', PASSWORD = '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi' WHERE EMPLOYEEID = 202;
UPDATE EMPLOYEE SET EMAIL = 'staff3@test.com', PASSWORD = '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi' WHERE EMPLOYEEID = 203;
UPDATE EMPLOYEE SET EMAIL = 'staff4@test.com', PASSWORD = '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi' WHERE EMPLOYEEID = 204;
UPDATE EMPLOYEE SET EMAIL = 'staff5@test.com', PASSWORD = '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi' WHERE EMPLOYEEID = 205;
UPDATE EMPLOYEE SET EMAIL = 'staff6@test.com', PASSWORD = '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi' WHERE EMPLOYEEID = 206;
UPDATE EMPLOYEE SET EMAIL = 'staff7@test.com', PASSWORD = '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi' WHERE EMPLOYEEID = 207;

COMMIT;

-- Step 3: Recreate the USERS view
CREATE OR REPLACE VIEW USERS AS
SELECT 
    EMPLOYEEID as USER_ID,
    EMAIL as EMAIL,
    EMPLOYEENAME as NAME,
    PASSWORD as PASSWORD,
    EMPLOYEEROLE as USER_ROLE,
    EMPLOYEEADDRESS as ADDRESS,
    EMPLOYEERATE as RATE,
    EMPLOYEEHIREDON as HIRED_ON,
    ANNUALLEAVEBALANCE as ANNUAL_LEAVE_BALANCE,
    SICKLEAVEBALANCE as SICK_LEAVE_BALANCE,
    EMERGENCYLEAVEBALANCE as EMERGENCY_LEAVE_BALANCE,
    SUPERVISOREMPLOYEEID as SUPERVISOR_ID,
    REMEMBER_TOKEN as REMEMBER_TOKEN,
    EMPLOYEENUMBER as PHONE,
    NULL as IC_NUMBER
FROM EMPLOYEE;

-- Step 4: Update triggers
CREATE OR REPLACE TRIGGER TRG_USERS_INSERT
INSTEAD OF INSERT ON USERS
FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENUMBER, EMAIL, EMPLOYEENAME, PASSWORD, EMPLOYEEROLE, EMPLOYEEADDRESS, EMPLOYEERATE, EMPLOYEEHIREDON, ANNUALLEAVEBALANCE, SICKLEAVEBALANCE, EMERGENCYLEAVEBALANCE, SUPERVISOREMPLOYEEID, REMEMBER_TOKEN)
    VALUES (
        NVL(:NEW.USER_ID, (SELECT NVL(MAX(EMPLOYEEID),0)+1 FROM EMPLOYEE)),
        :NEW.PHONE,
        :NEW.EMAIL,
        :NEW.NAME,
        :NEW.PASSWORD,
        NVL(:NEW.USER_ROLE, 'Staff'),
        :NEW.ADDRESS,
        NVL(:NEW.RATE, 3000),
        NVL(:NEW.HIRED_ON, SYSDATE),
        NVL(:NEW.ANNUAL_LEAVE_BALANCE, 14),
        NVL(:NEW.SICK_LEAVE_BALANCE, 10),
        NVL(:NEW.EMERGENCY_LEAVE_BALANCE, 5),
        :NEW.SUPERVISOR_ID,
        :NEW.REMEMBER_TOKEN
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_USERS_UPDATE
INSTEAD OF UPDATE ON USERS
FOR EACH ROW
BEGIN
    UPDATE EMPLOYEE SET
        EMPLOYEENUMBER = :NEW.PHONE,
        EMAIL = :NEW.EMAIL,
        EMPLOYEENAME = :NEW.NAME,
        PASSWORD = :NEW.PASSWORD,
        EMPLOYEEROLE = :NEW.USER_ROLE,
        EMPLOYEEADDRESS = :NEW.ADDRESS,
        EMPLOYEERATE = :NEW.RATE,
        EMPLOYEEHIREDON = :NEW.HIRED_ON,
        ANNUALLEAVEBALANCE = :NEW.ANNUAL_LEAVE_BALANCE,
        SICKLEAVEBALANCE = :NEW.SICK_LEAVE_BALANCE,
        EMERGENCYLEAVEBALANCE = :NEW.EMERGENCY_LEAVE_BALANCE,
        SUPERVISOREMPLOYEEID = :NEW.SUPERVISOR_ID,
        REMEMBER_TOKEN = :NEW.REMEMBER_TOKEN
    WHERE EMPLOYEEID = :OLD.USER_ID;
END;
/

COMMIT;

-- Show results
SELECT EMPLOYEEID, EMAIL, EMPLOYEENAME, EMPLOYEEROLE FROM EMPLOYEE ORDER BY EMPLOYEEID;
