-- Oracle Views for Laravel Compatibility
-- Run this in Oracle as VITALITY user

-- Drop existing views if they exist
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW USERS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW ATTENDANCES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW SHIFT_SCHEDULES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW LEAVE_REQUESTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- USERS view (maps from EMPLOYEE table)
CREATE OR REPLACE VIEW USERS AS
SELECT 
    EMPLOYEEID as USER_ID,
    EMPLOYEENUMBER as EMAIL,
    EMPLOYEENAME as NAME,
    EMPLOYEEROLE as USER_ROLE,
    EMPLOYEEADDRESS as ADDRESS,
    EMPLOYEERATE as RATE,
    EMPLOYEEHIREDON as HIRED_ON,
    ANNUALLEAVEBALANCE as ANNUAL_LEAVE_BALANCE,
    SICKLEAVEBALANCE as SICK_LEAVE_BALANCE,
    EMERGENCYLEAVEBALANCE as EMERGENCY_LEAVE_BALANCE,
    SUPERVISOREMPLOYEEID as SUPERVISOR_ID,
    -- Add phone and ic_number as NULL since not in Oracle schema
    NULL as PHONE,
    NULL as IC_NUMBER,
    NULL as PASSWORD,
    NULL as REMEMBER_TOKEN
FROM EMPLOYEE;

-- SHIFT_SCHEDULES view (maps from SHIFT table)
CREATE OR REPLACE VIEW SHIFT_SCHEDULES AS
SELECT 
    SHIFTID as SHIFT_ID,
    EMPLOYEEID as USER_ID,
    SHIFTDATE as SHIFT_DATE,
    LOWER(SHIFTTYPE) as SHIFT_TYPE
FROM SHIFT;

-- ATTENDANCES view (maps from ATTENDANCE table)
CREATE OR REPLACE VIEW ATTENDANCES AS
SELECT 
    ATTENDANCEID as ATTENDANCE_ID,
    SHIFTID as SHIFT_ID,
    EMPLOYEEID as USER_ID,
    LOWER(STATUS) as STATUS,
    CLOCKINTIME as CLOCK_IN_TIME,
    CLOCKOUTTIME as CLOCK_OUT_TIME
FROM ATTENDANCE;

-- LEAVE_REQUESTS view (maps from LEAVEREQUEST table)
CREATE OR REPLACE VIEW LEAVE_REQUESTS AS
SELECT 
    REQUESTID as REQUEST_ID,
    EMPLOYEEID as USER_ID,
    TYPE as TYPE,
    STARTDATE as START_DATE,
    ENDDATE as END_DATE,
    CASE LEAVESTATUS 
        WHEN 'Pending' THEN 0
        WHEN 'Approved' THEN 1
        WHEN 'Rejected' THEN 2
        ELSE 0 
    END as STATUS,
    REMARK as REMARK
FROM LEAVEREQUEST;

-- Grant permissions
GRANT SELECT ON USERS TO VITALITY;
GRANT SELECT ON ATTENDANCES TO VITALITY;
GRANT SELECT ON SHIFT_SCHEDULES TO VITALITY;
GRANT SELECT ON LEAVE_REQUESTS TO VITALITY;

-- =============================================
-- INSTEAD OF TRIGGERS FOR INSERT/UPDATE/DELETE
-- =============================================

-- USERS (EMPLOYEE) - INSERT
CREATE OR REPLACE TRIGGER TRG_USERS_INSERT
INSTEAD OF INSERT ON USERS
FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEE (EMPLOYEEID, EMPLOYEENUMBER, EMPLOYEENAME, EMPLOYEEROLE, EMPLOYEEADDRESS, EMPLOYEERATE, EMPLOYEEHIREDON, ANNUALLEAVEBALANCE, SICKLEAVEBALANCE, EMERGENCYLEAVEBALANCE, SUPERVISOREMPLOYEEID)
    VALUES (
        NVL(:NEW.USER_ID, (SELECT NVL(MAX(EMPLOYEEID),0)+1 FROM EMPLOYEE)),
        :NEW.EMAIL,
        :NEW.NAME,
        NVL(:NEW.USER_ROLE, 'Staff'),
        :NEW.ADDRESS,
        NVL(:NEW.RATE, 0),
        NVL(:NEW.HIRED_ON, SYSDATE),
        NVL(:NEW.ANNUAL_LEAVE_BALANCE, 14),
        NVL(:NEW.SICK_LEAVE_BALANCE, 10),
        NVL(:NEW.EMERGENCY_LEAVE_BALANCE, 5),
        :NEW.SUPERVISOR_ID
    );
END;
/

-- USERS (EMPLOYEE) - UPDATE
CREATE OR REPLACE TRIGGER TRG_USERS_UPDATE
INSTEAD OF UPDATE ON USERS
FOR EACH ROW
BEGIN
    UPDATE EMPLOYEE SET
        EMPLOYEENUMBER = :NEW.EMAIL,
        EMPLOYEENAME = :NEW.NAME,
        EMPLOYEEROLE = :NEW.USER_ROLE,
        EMPLOYEEADDRESS = :NEW.ADDRESS,
        EMPLOYEERATE = :NEW.RATE,
        EMPLOYEEHIREDON = :NEW.HIRED_ON,
        ANNUALLEAVEBALANCE = :NEW.ANNUAL_LEAVE_BALANCE,
        SICKLEAVEBALANCE = :NEW.SICK_LEAVE_BALANCE,
        EMERGENCYLEAVEBALANCE = :NEW.EMERGENCY_LEAVE_BALANCE,
        SUPERVISOREMPLOYEEID = :NEW.SUPERVISOR_ID
    WHERE EMPLOYEEID = :OLD.USER_ID;
END;
/

-- USERS (EMPLOYEE) - DELETE
CREATE OR REPLACE TRIGGER TRG_USERS_DELETE
INSTEAD OF DELETE ON USERS
FOR EACH ROW
BEGIN
    DELETE FROM EMPLOYEE WHERE EMPLOYEEID = :OLD.USER_ID;
END;
/

-- SHIFT_SCHEDULES (SHIFT) - INSERT
CREATE OR REPLACE TRIGGER TRG_SHIFTS_INSERT
INSTEAD OF INSERT ON SHIFT_SCHEDULES
FOR EACH ROW
BEGIN
    INSERT INTO SHIFT (SHIFTID, EMPLOYEEID, SHIFTDATE, SHIFTTYPE)
    VALUES (
        NVL(:NEW.SHIFT_ID, (SELECT NVL(MAX(SHIFTID),0)+1 FROM SHIFT)),
        :NEW.USER_ID,
        :NEW.SHIFT_DATE,
        INITCAP(:NEW.SHIFT_TYPE)
    );
END;
/

-- SHIFT_SCHEDULES (SHIFT) - UPDATE
CREATE OR REPLACE TRIGGER TRG_SHIFTS_UPDATE
INSTEAD OF UPDATE ON SHIFT_SCHEDULES
FOR EACH ROW
BEGIN
    UPDATE SHIFT SET
        EMPLOYEEID = :NEW.USER_ID,
        SHIFTDATE = :NEW.SHIFT_DATE,
        SHIFTTYPE = INITCAP(:NEW.SHIFT_TYPE)
    WHERE SHIFTID = :OLD.SHIFT_ID;
END;
/

-- SHIFT_SCHEDULES (SHIFT) - DELETE
CREATE OR REPLACE TRIGGER TRG_SHIFTS_DELETE
INSTEAD OF DELETE ON SHIFT_SCHEDULES
FOR EACH ROW
BEGIN
    DELETE FROM SHIFT WHERE SHIFTID = :OLD.SHIFT_ID;
END;
/

-- ATTENDANCES (ATTENDANCE) - INSERT
CREATE OR REPLACE TRIGGER TRG_ATTENDANCES_INSERT
INSTEAD OF INSERT ON ATTENDANCES
FOR EACH ROW
BEGIN
    INSERT INTO ATTENDANCE (ATTENDANCEID, SHIFTID, EMPLOYEEID, STATUS, CLOCKINTIME, CLOCKOUTTIME)
    VALUES (
        NVL(:NEW.ATTENDANCE_ID, (SELECT NVL(MAX(ATTENDANCEID),0)+1 FROM ATTENDANCE)),
        :NEW.SHIFT_ID,
        :NEW.USER_ID,
        UPPER(:NEW.STATUS),
        :NEW.CLOCK_IN_TIME,
        :NEW.CLOCK_OUT_TIME
    );
END;
/

-- ATTENDANCES (ATTENDANCE) - UPDATE
CREATE OR REPLACE TRIGGER TRG_ATTENDANCES_UPDATE
INSTEAD OF UPDATE ON ATTENDANCES
FOR EACH ROW
BEGIN
    UPDATE ATTENDANCE SET
        SHIFTID = :NEW.SHIFT_ID,
        EMPLOYEEID = :NEW.USER_ID,
        STATUS = UPPER(:NEW.STATUS),
        CLOCKINTIME = :NEW.CLOCK_IN_TIME,
        CLOCKOUTTIME = :NEW.CLOCK_OUT_TIME
    WHERE ATTENDANCEID = :OLD.ATTENDANCE_ID;
END;
/

-- ATTENDANCES (ATTENDANCE) - DELETE
CREATE OR REPLACE TRIGGER TRG_ATTENDANCES_DELETE
INSTEAD OF DELETE ON ATTENDANCES
FOR EACH ROW
BEGIN
    DELETE FROM ATTENDANCE WHERE ATTENDANCEID = :OLD.ATTENDANCE_ID;
END;
/

-- LEAVE_REQUESTS (LEAVEREQUEST) - INSERT
CREATE OR REPLACE TRIGGER TRG_LEAVE_REQUESTS_INSERT
INSTEAD OF INSERT ON LEAVE_REQUESTS
FOR EACH ROW
BEGIN
    INSERT INTO LEAVEREQUEST (REQUESTID, EMPLOYEEID, TYPE, STARTDATE, ENDDATE, LEAVESTATUS, REMARK)
    VALUES (
        NVL(:NEW.REQUEST_ID, (SELECT NVL(MAX(REQUESTID),0)+1 FROM LEAVEREQUEST)),
        :NEW.USER_ID,
        :NEW.TYPE,
        :NEW.START_DATE,
        :NEW.END_DATE,
        CASE :NEW.STATUS WHEN 0 THEN 'Pending' WHEN 1 THEN 'Approved' WHEN 2 THEN 'Rejected' ELSE 'Pending' END,
        :NEW.REMARK
    );
END;
/

-- LEAVE_REQUESTS (LEAVEREQUEST) - UPDATE
CREATE OR REPLACE TRIGGER TRG_LEAVE_REQUESTS_UPDATE
INSTEAD OF UPDATE ON LEAVE_REQUESTS
FOR EACH ROW
BEGIN
    UPDATE LEAVEREQUEST SET
        EMPLOYEEID = :NEW.USER_ID,
        TYPE = :NEW.TYPE,
        STARTDATE = :NEW.START_DATE,
        ENDDATE = :NEW.END_DATE,
        LEAVESTATUS = CASE :NEW.STATUS WHEN 0 THEN 'Pending' WHEN 1 THEN 'Approved' WHEN 2 THEN 'Rejected' ELSE 'Pending' END,
        REMARK = :NEW.REMARK
    WHERE REQUESTID = :OLD.REQUEST_ID;
END;
/

-- LEAVE_REQUESTS (LEAVEREQUEST) - DELETE
CREATE OR REPLACE TRIGGER TRG_LEAVE_REQUESTS_DELETE
INSTEAD OF DELETE ON LEAVE_REQUESTS
FOR EACH ROW
BEGIN
    DELETE FROM LEAVEREQUEST WHERE REQUESTID = :OLD.REQUEST_ID;
END;
/

COMMIT;
